# Generated by Django 2.0.4 on 2018-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='illness',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='casenumber',
            field=models.CharField(max_length=10),
        ),
    ]
