# Generated by Django 2.0.4 on 2018-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0002_auto_20180503_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='illness',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
