# Generated by Django 2.0.4 on 2018-05-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0003_auto_20180503_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='illness',
            new_name='diagnosis',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='symptoms',
        ),
        migrations.AddField(
            model_name='patient',
            name='trimester',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
