# Generated by Django 2.0.4 on 2018-05-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0004_auto_20180503_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='casenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='trimester',
            field=models.CharField(max_length=20),
        ),
    ]
