# Generated by Django 2.0.4 on 2018-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0005_auto_20180503_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='symptoms',
            new_name='symptom1',
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom5',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
