# Generated by Django 2.0.4 on 2018-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0007_auto_20180509_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom1', models.CharField(max_length=30)),
                ('symptom2', models.CharField(blank=True, max_length=30)),
                ('symptom3', models.CharField(blank=True, max_length=30)),
                ('symptom4', models.CharField(blank=True, max_length=30)),
                ('symptom5', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom3',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom4',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptom5',
        ),
    ]
