# Generated by Django 2.0.4 on 2018-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0008_auto_20180509_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.ManyToManyField(to='lmdf.Symptoms'),
        ),
    ]
