# Generated by Django 2.0.4 on 2018-05-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0009_patient_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptoms',
            old_name='symptom1',
            new_name='symptom',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='symptom2',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='symptom3',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='symptom4',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='symptom5',
        ),
    ]
