# Generated by Django 2.0.4 on 2018-05-09 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0010_auto_20180509_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='trimester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmdf.Trimester'),
        ),
    ]
