# Generated by Django 2.0.4 on 2018-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmdf', '0015_auto_20180510_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_fr',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptoms',
            name='symptom_fr',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
